### PR TITLE
Possibility to mute the assistant

### PR DESCRIPTION
**Pull request by CITMark**
I've added the possibility to mute the assistant. This is done with help of someone of Daily.

We mute the "Vapi Speaker" so no sounds get's through and you can have a silent interaction with an assistant if needed.

### CODE REVIEW

**Review by nikhilro — COMMENTED** [review]
Appreciate it!

I think we'll want to use `.send` though

Example, in [web sdk](https://github.com/VapiAI/web), we use 
```
vapi.send({
  type: 'add-message',
  message: {
    role: 'system',
    content: 'The user has pressed the button, say peanuts',
  },
});
```

Muting assistant is already a primitive supported in send: https://docs.vapi.ai/api-reference/messages/client-inbound-message

**Comment by CITMark** [comment]
@nikhilro 

Maybe I'm explaining the functionality incorrectly. But what happens here is that you actually no longer have any incoming sound from the assistant. So you no longer have any sound, but you still have the normal speech events. So this actually comes down to how ChatGPT works. Purely and only text. This can be useful, for example, if you are in a room where you cannot talk at the moment and can only type temporarily.

I know that you can already send messages via the client. But this ensures that you can mute the incoming sound. The same as you can mute your own sound with the normal mute action that is already in the SDK.

**Comment by nikhilro** [comment]
we're on the same page. 
```
{
  "message": {
    "type": "control",
    "control:  "mute-assistant"
    }
}
```

**Comment by CITMark** [comment]
Just tried this and this does not reflect what I intended here and what I created does.

In your example:
It actually interrupts the voice assistant and no new data comes in, so it breaks off in the middle of the sentence, so it's completely muted the "speaker" and the "listener". So no new transcript events come in

In my example:
It just interrupts the sound, so no more sounds does come through, but the listener is still active. So this means that transcript events actually do come through. And you can for example still show the text of what the assistant is saying. In the `control` type message. We can't show the text anymore, because the assistant is muted completely.

I want the sound to be muted but the events to still come through. That's what this PR does.

Thanks for pointing out the different kind of messages, because didn't know that was possible, reminds me immediately of reading the documentation more often so we can extend the iOS library. But in this case it doesn't resolve the use case.

**Review by nikhilro — APPROVED** [review]

**Comment by nikhilro** [comment]
sounds good, thanks for explaining!

**Pull request merged**
